spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      schema: app_schema

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    contexts: dev
    liquibase-schema: public
    default-schema: app_schema
    drop-first: false

jwt:
  # The secret key used to sign the JWT. Ensure this is long enough (at least 32 characters)
  # and kept secure. Do not expose it publicly.
  secret: "verysecureandlongsecretkeyforjwtorderserviceapp"

  # The token expiration time in seconds.
  # In this case, 3600 seconds equals 1 hour (60 minutes * 60 seconds).
  expiration: 3600